apiVersion: v1
kind: Pod
metadata:
  name: helloworld-skaffold
spec:
  hostNetwork: true
  containers:
  - name: helloworld-skaffold
    image: osanz/helloworld-skaffold
    ports:
    - containerPort: 8082
      hostPort: 8082
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
